engines:
  phpcodesniffer:
    enabled: false
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - script/**
  - src/**
exclude_paths:
- web/**